version: "3.7"

services:
  db:
    build: .
    restart: always
    ports:
      - 33006:3306
    environment:
      - MYSQL_ROOT_PASSWORD=itMustBeAVeryStrongPassword
      - MYSQL_DATABASE=realise_biblio
      - MYSQL_USER=realise
      - MYSQL_PASSWORD=realise1234

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - 8989:80
    environment:
      - PMA_ARBITRARY=1

